### Dimension, Shape, Size

In [58]:
import numpy as np

# create array
a = np.array([1,2,3], dtype='int32') # 1D <== a.ndim=1
b = np.array([ [9.0,8.0,7.0],[6.0,5.0,4] ]) # 2D <== b.ndim=2
c = np.array([ [[1],[3],[4]] , [[5],[7],[2]] ]) # 3D <== c.ndim=3

# type = dtype('float64')
b.dtype

# number of elements = 6
b.size

# dimension = 2
b.ndim

# shape = (2, 3, 1)
c.shape

(2, 3, 1)

### Accese Elements, Rows, Columns

In [79]:
d= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

# Get a specific element 
d[1, 5]

# Get a specific row 
d[0, :]

# Get a specific column
d[:, 2]

# Fancy [start:end:step]
print(d[0, 1:-1:2])

# change elements
d[1,5] = 20
d[:,2] = [1,2]

# 3D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 

# Get specific element
print(c[0,1,1])

# replace 
c[:,1,:] = [[9,9],[8,8]]

print(c)

[2 4 6]


### Initialize Different Arrays

In [159]:
# All 0 matrix
np.zeros((2,3))

# All 1 matrix
np.ones((4,2,2), dtype='int32')

# Identity matrix
np.identity(5)

# 2*2 matrix full of 99
np.full((2,2), 99)

# d.shape matrix full of 99 
np.full_like(d, 99)

# lD array start:end:count 
np.linspace(5, 15, 3) # array([ 5., 10., 15.])

# 1D array from 0 to 4 
np.arange(5) # array([0, 1, 2, 3, 4])

# 100 random numbers with normal distribution (mean 0 and variance 1)
np.random.randn(100)

#N(mu, sigma^2)= sigma * np.random.randn() + mu
10* np.random.randn(100) +20 # 100 Gaussian distributin  

# 4*2 matrix of 0<rand<1
np.random.rand(4,2)
np.random.random_sample((4,2))

# 3*3 matrix of -4<int_rand<8
np.random.randint(-4,8, size=(3,3))
np.random.randint(0,30,5)
# Repeat an array
x = np.array([[1,2,3]])
y = np.repeat(x,3, axis=0)

# Copy an array
z=y.copy()

# reshape
A = np.array([[1,2,3,4],[5,6,7,8]])
A.reshape((1,4,2))


v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

# Vertical stack
print(np.vstack((v1,v2)))

# Horizontal stack
print(np.hstack((v1,v2)))


[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### Mathematics, Linear Algebra, Statistics

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])

a + 2   # = array([3, 4, 5, 6])
a ** 2  # = array([1, 4, 9, 16])
a + b   # = array([2, 2, 4, 4])
np.cos(a)  

#https://docs.scipy.org/doc/numpy/reference/routines.math.html

from numpy import linalg

a = np.ones((2,3))
b = np.full((3,2), 2)

# Matrix Multiplication
c = np.matmul(a,b)

# Matrix Determinant
np.linalg.det(c)

# Trace
np.trace(c)

# Eigenvectors
linalg.eig(c)

# Singular Vector Decomposition, Eigenvalues, Matrix Norm, Inverse
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

stats = np.array([[1,8,3],[4,5,6]])
np.min(stats)
np.max(stats, axis=0)
np.sum(stats, axis=1)

### Load File and Mask

In [175]:
# read txt, convert into integer 
d = np.genfromtxt('data.txt', delimiter=',')
d = d.astype('int32')

# Masking and Filtering
filt1= (~((d > 50) & (d < 100)))
filt2 = (d % 4 == 0)
print(d[filt2])

[196   4   8   0   4  12   4   4   4   0  12   0   8  76  88]


In [186]:
d= np.linspace(1, 30, 30).reshape(6, 5)

d[[0, 4, 5], 3:]

array([[ 4.,  5.],
       [24., 25.],
       [29., 30.]])